title: ChenYang Li's Homepage
page-top-title: ChenYang Li
#top-section-bg-text: Computer Science
home-subtitle: ChenYang Li&ensp;|&ensp;李晨阳
copyright-text: '&copy; ChenYang Li 2025-2026. All Rights Reserved.'
